name: Chromatic

permissions:
  contents: read

on:
  push:
    paths:
      - clients/**
      - .github/workflows/chromatic.yaml

jobs:
  chromatic-deployment:
    name: "Publish ðŸŽ¨"
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0 # chromatic requires the full history for it's smartness

      - uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version-file: clients/.node-version
          cache: "pnpm"
          cache-dependency-path: "clients/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: ./clients
        run: pnpm install

      - name: Build SDK
        working-directory: ./clients
        run: pnpm turbo run build --filter=@polar-sh/*

      - name: Publish to Chromatic
        uses: chromaui/action@v13
        with:
          projectToken: ${{ secrets.CI_CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./clients/apps/web
          onlyChanged: true
          exitOnceUploaded: true
