name: Release Chrome Extension

on:
  workflow_dispatch: {}

jobs:
  build-chrome-extension:
    name: Build Chrome extension artifact
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.7.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: clients/.node-version
          cache: "pnpm"
          cache-dependency-path: "clients/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: ./clients/apps/chrome-extension
        run: pnpm install

      - name: Build
        working-directory: ./clients/apps/chrome-extension
        run: |-
          pnpm build:prod
          # we archive the dist folder and include SHA commit as the last step
          zip -r chrome-extension-${{ github.sha }}.zip extension

      - name: Archive chrome-extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: chrome-extension-${{ github.sha }}
          path: ./clients/apps/chrome-extension/chrome-extension-${{ github.sha }}.zip

  # api usage reference:
  # * <https://developer.chrome.com/docs/webstore/using_webstore_api/>
  # * <https://github.com/fregante/chrome-webstore-upload/blob/main/How%20to%20generate%20Google%20API%20keys.md>
  upload-extension:
    name: Upload extension
    runs-on: ubuntu-22.04
    needs: build-chrome-extension
    env:
      EXTENSION_ID: flgggfbldmglpjmagkhlhiohnkcmgbhi

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: v18

      - name: Download bundle artifact
        uses: actions/download-artifact@v3
        with:
          name: chrome-extension-${{ github.sha }}

      - name: Install webstore cli
        run: |-
          npm install -g chrome-webstore-upload-cli

      - name: Upload step
        env:
          CLIENT_ID: ${{ secrets.CI_GOOGLE_CHROME_WEBSTORE_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CI_GOOGLE_CHROME_WEBSTORE_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.CI_GOOGLE_CHROME_WEBSTORE_REFRESH_TOKEN }}
        run: chrome-webstore-upload upload --source chrome-extension-${{ github.sha }}.zip --extension-id ${{ env.EXTENSION_ID }}
