name: Client

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, edited]

permissions:
  contents: read

jobs:
  build:
    name: "Client: Tests ðŸŽ¨"
    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      VERCEL_ENV: "testing"

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        with:
          version: 10.13.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version-file: clients/.node-version
          cache: "pnpm"
          cache-dependency-path: "clients/pnpm-lock.yaml"

      - name: Install dependencies
        working-directory: ./clients
        run: pnpm install

      - uses: actions/cache@v4
        with:
          path: |
            ./clients/apps/web/.next
          key: next-${{ hashFiles('./clients/pnpm-lock.yaml') }}-${{ github.sha }}
          restore-keys: |
            next-${{ hashFiles('./clients/pnpm-lock.yaml') }}-
            next-

      - name: Lint
        working-directory: ./clients
        run: pnpm run lint

      - name: Typecheck
        working-directory: ./clients
        run: pnpm run typecheck

      - name: Build
        working-directory: ./clients
        run: pnpm build
