name: Client

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, edited]

defaults:
  run:
    working-directory: ./clients

permissions:
  contents: read

jobs:
  changes:
    name: "Detect changes"
    runs-on: ubuntu-latest
    outputs:
      clients: ${{ steps.filter.outputs.clients }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            clients:
              - 'clients/**'
              - '.github/workflows/test_client.yaml'

  build:
    name: "Client: Tests ğŸ¨"
    needs: changes
    if: needs.changes.outputs.clients == 'true'
    timeout-minutes: 15
    runs-on: ubuntu-latest

    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      VERCEL_ENV: "testing"

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: clients/package.json

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: clients/.node-version
          cache: "pnpm"
          cache-dependency-path: "clients/pnpm-lock.yaml"

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ’…Lint
        run: pnpm run lint

      - name: ğŸ‘€ Typecheck
        run: pnpm run typecheck

      - name: "ğŸ§ª Test: App"
        run: pnpm --filter @polar-sh/app test

      - name: ğŸ› ï¸ Build
        run: pnpm build
